// Test Math built-in
print(Math.abs(-5));
print(Math.abs(5));
print(Math.floor(3.7));
print(Math.floor(-3.7));
print(Math.ceil(3.2));
print(Math.ceil(-3.2));
print(Math.round(3.5));
print(Math.round(3.4));
print(Math.sqrt(16));
print(Math.sqrt(2));
print(Math.pow(2, 3));
print(Math.pow(4, 0.5));
print(Math.min(1, 2, 3));
print(Math.max(1, 2, 3));
const randomValue = Math.random();
print(typeof randomValue);
print(randomValue >= 0);
print(randomValue < 1);
print(Math.sin(0));
print(Math.cos(0));
print(Math.tan(0));
print(1 / -0);
print(Object.is(-0, -0));
print(Object.is(0, -0));
print(Object.is(1, 1.5 - 0.5));
print(typeof Math.acosh);
print(Math.acosh(1));
print(Math.asinh(0));
print(Math.atanh(0));
print(Math.acosh(0));
print(Math.atanh(2));
