// Test Number built-in
print(Number.parseInt("42"));
print(Number.parseFloat("3.14"));
print(Number.NaN);
print(Number.POSITIVE_INFINITY);
print(Number.NEGATIVE_INFINITY);
print(typeof globalThis);
print(globalThis.globalThis === globalThis);
print(globalThis.Math === Math);
print(parseInt("0x10"));
print(parseInt("0x10", 16));
print(parseInt("0x10", 10));
print(parseInt("-0xF"));
print(parseInt("+0xF"));
print(parseInt("10", 1));
print(parseInt("10", 37));
print(parseInt("12px"));
print(1 / parseInt("-0"));
print(parseFloat("1.5x"));
print(parseFloat("+.5x"));
print(parseFloat("Infinityx"));
print(parseFloat("-Infinityx"));
print(parseFloat("x1"));
print(1 / parseFloat("-0"));
