#!/usr/bin/env python3
"""P7-50 closure-allocation case generator.

Emits the same-runtime case matrix used to attribute the per-iteration closure
allocation gap. Every case is a callable `run()` so the shared
`tools/perf/same_runtime` harnesses compile the source once and invoke the
retained function repeatedly; parser, compile and process startup are therefore
outside the compared region.

Two axes:

* shape -- what the loop body creates (nothing / non-capturing arrow /
  non-capturing function expression / one captured outer local / four captured
  outer locals / a fresh per-iteration lexical binding / create-then-call).
* lifetime -- `churn` overwrites one slot per iteration, so each iteration pays
  one creation plus the previous closure's release. `retain` alternates whole
  `run()` calls between a fill phase (N creations into already-null preallocated
  slots, no release) and a clear phase (N releases, no creation), so the
  harness's per-sample timing separates creation from destruction. A refcounted
  engine cannot create N objects per iteration and release none in steady
  state, so phase alternation is the only way to put the release outside the
  timed region while the harness times exactly one `run()` call.

Both lifetimes store through an ARRAY ELEMENT (`slot[0]` / `slots[i]`), never
through a bare identifier. That is deliberate topology equalisation: an
assignment whose target is an IdentifierReference triggers NamedEvaluation, so
`g = (x) => x + 1` makes the engine define `name` a SECOND time (measured: one
extra `JS_DefinePropertyValue` and one extra `JS_AtomToString` in qjs, one extra
`defineOwnProperty` / `functionNameValueFromAtom` / `cloneShape` /
`ensureUniqueShapeForMutation` in zjs). That is a source-shape artefact of the
assignment target, not a closure-creation mechanism, and it would have made the
churn-vs-retain difference uninterpretable as teardown cost. A member-expression
target performs no NamedEvaluation, so both lifetimes now do exactly two
property defines per created closure.

The retain phase parity is a pure function of the call index, so
`--warmup W --iterations I` makes the sample phases deterministic: with even W
the first sample is a fill.

None of these cases is a policy sentinel (same reason as `local_arith_loop`):
adding them to `policy.json` would move the P0 exit-line geomean.
"""

import argparse
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CASES = os.path.abspath(
    os.path.join(HERE, "..", "same_runtime", "cases")
)

N_DEFAULT = 20000

HEADER = (
    "// P7-50 closure-allocation probe, not a policy sentinel (see\n"
    "// tools/perf/same_runtime/cases/README.md). Generated by\n"
    "// tools/perf/closure_alloc/gen_cases.py -- edit the generator, not this\n"
    "// file.\n"
)

# shape name -> (pre-loop declarations, per-iteration expression, extra
#                per-iteration statement, checksum expression for a filled
#                slot, notes)
SHAPES = {
    "reuse": {
        "decls": "const F = (x) => x + 1;\n",
        "expr": "F",
        "extra": "",
        "desc": "reuse-precreated: one function created once at module scope, "
                "no closure creation in the loop -- the baseline",
    },
    "arrow_nocap": {
        "decls": "",
        "expr": "(x) => x + 1",
        "extra": "",
        "desc": "arrow-no-capture: non-capturing arrow created every iteration",
    },
    "fnexpr_nocap": {
        "decls": "",
        "expr": "function (x) { return x + 1; }",
        "extra": "",
        "desc": "function-no-capture: non-capturing function expression "
                "created every iteration",
    },
    "arrow_cap1": {
        "decls": "",
        "expr": "(x) => x + k0",
        "extra": "",
        "locals": 1,
        "desc": "arrow-capture-outer: captures one already-existing outer "
                "local of run()",
    },
    "fnexpr_cap1": {
        "decls": "",
        "expr": "function (x) { return x + k0; }",
        "extra": "",
        "locals": 1,
        "desc": "function-capture-outer: same single capture as "
                "arrow_cap1 but an ordinary function expression",
    },
    "arrow_cap4": {
        "decls": "",
        "expr": "(x) => x + k0 + k1 + k2 + k3",
        "extra": "",
        "locals": 4,
        "desc": "arrow-capture-4: captures four already-existing outer locals, "
                "for the closure-slot slope",
    },
    "arrow_loopbind": {
        "decls": "",
        "expr": "() => i",
        "extra": "",
        "desc": "arrow-loop-binding: captures the per-iteration `let i`, which "
                "forces a FRESH lexical binding per iteration. SEMANTICALLY "
                "HEAVIER than every other shape -- not a like-for-like "
                "comparison with arrow_cap1",
    },
    "arrow_call": {
        "decls": "",
        "expr": "(x) => x + 1",
        "extra": "acc += TARGET(1);",
        "desc": "arrow-create-and-call: create then immediately call, to see "
                "whether allocation and call cost add",
    },
    # P7-40 cross-check pair. These two reproduce P7-40's `closure_only`
    # source shape exactly -- the assignment target is a bare IdentifierReference
    # -- so the difference against arrow_nocap / reuse isolates the
    # NamedEvaluation `name` re-define that the array-element target avoids.
    # churn-only: a bare identifier cannot express the retain lifetime.
    "identtarget_reuse": {
        "decls": "const F = (x) => x + 1;\n",
        "expr": "F",
        "extra": "",
        "target": "g",
        "churn_only": True,
        "desc": "P7-40 cross-check baseline: identifier assignment target, "
                "reusing one precreated function",
    },
    "identtarget_nocap": {
        "decls": "",
        "expr": "(x) => x + 1",
        "extra": "",
        "target": "g",
        "churn_only": True,
        "desc": "P7-40 cross-check: identifier assignment target, so the arrow "
                "is subject to NamedEvaluation and pays a second name define",
    },
}

ORDER = [
    "reuse",
    "arrow_nocap",
    "fnexpr_nocap",
    "arrow_cap1",
    "fnexpr_cap1",
    "arrow_cap4",
    "arrow_loopbind",
    "arrow_call",
    "identtarget_reuse",
    "identtarget_nocap",
]


def local_decls(count):
    if not count:
        return ""
    return "".join(
        "    const k%d = %d;\n" % (i, i + 1) for i in range(count)
    )


def churn_case(name, shape, n):
    locals_src = local_decls(shape.get("locals", 0))
    target = shape.get("target", "slot[0]")
    slot_decl = ("let g = null;\n" if target == "g" else "const slot = [null];\n")
    extra = shape["extra"].replace("TARGET", target)
    extra_src = "        %s\n" % extra if extra else ""
    body = (
        "%s%s"
        "const N = %d;\n"
        "%s"
        "%s"
        "let calls = 0;\n"
        "let acc = 0;\n"
        "function run() {\n"
        "%s"
        "    calls += 1;\n"
        "    acc = 0;\n"
        "    for (let i = 0; i < N; i++) {\n"
        "        %s = %s;\n"
        "%s"
        "    }\n"
        "    return calls * 1000000 + acc * 1000 + %s(1);\n"
        "}\n"
    ) % (
        HEADER,
        "// %s\n// lifetime churn: one slot overwritten per iteration, so each\n"
        "// iteration is one creation plus the previous closure's release.\n"
        "// Assignment target: %s (see generator header on NamedEvaluation).\n"
        % (shape["desc"], target),
        n,
        shape["decls"],
        slot_decl,
        locals_src,
        target,
        shape["expr"],
        extra_src,
        target,
    )
    return body


def retain_case(name, shape, n):
    locals_src = local_decls(shape.get("locals", 0))
    extra = shape["extra"].replace("TARGET", "slots[i]")
    extra_src = "            %s\n" % extra if extra else ""
    body = (
        "%s%s"
        "const N = %d;\n"
        "%s"
        "const slots = new Array(N);\n"
        "for (let i = 0; i < N; i++) slots[i] = null;\n"
        "let calls = 0;\n"
        "let acc = 0;\n"
        "function run() {\n"
        "%s"
        "    calls += 1;\n"
        "    acc = 0;\n"
        "    if ((calls & 1) === 1) {\n"
        "        for (let i = 0; i < N; i++) {\n"
        "            slots[i] = %s;\n"
        "%s"
        "        }\n"
        "        return calls * 1000000 + acc * 1000 + slots[N - 1](1);\n"
        "    }\n"
        "    for (let i = 0; i < N; i++) slots[i] = null;\n"
        "    return calls * 1000000;\n"
        "}\n"
    ) % (
        HEADER,
        "// %s\n// lifetime retain: odd run() calls fill N already-null\n"
        "// preallocated slots (N creations, no release); even run() calls\n"
        "// clear them (N releases, no creation). The harness times one run()\n"
        "// call per sample, so with an even --warmup the odd-indexed samples\n"
        "// are creation-only and the even-indexed samples are release-only.\n"
        % shape["desc"],
        n,
        shape["decls"],
        locals_src,
        shape["expr"],
        extra_src,
    )
    return body


IDENTITY_PROBE = HEADER + '''// P7-50 semantic probe. The perf cases checksum only one closure, so an
// engine that hoisted the loop-body function expression out of the loop, or
// cached and reused one function object, would silently look fast. This probe
// runs in the SAME layer (retained callable, source compiled once) and proves
// that every evaluation of each shape produces a DISTINCT Function identity,
// and that each capturing shape observes the value it is supposed to observe.
//
// run() throws on any violation, which the harness reports as a fatal engine
// error, so a passing perf run of this case is the proof.
const K = 64;

function distinct(list) {
    for (let i = 0; i < list.length; i++) {
        if (typeof list[i] !== "function") return false;
        for (let j = i + 1; j < list.length; j++) {
            if (list[i] === list[j]) return false;
        }
    }
    return true;
}

function fail(what) {
    throw new Error("P7-50 identity probe failed: " + what);
}

let calls = 0;

function run() {
    calls += 1;
    const k0 = 1, k1 = 2, k2 = 3, k3 = 4;

    // reuse-precreated is the one shape that MUST be identical every time.
    const F = (x) => x + 1;
    const reuse = [];
    for (let i = 0; i < K; i++) reuse.push(F);
    for (let i = 0; i < K; i++) if (reuse[i] !== F) fail("reuse identity");
    if (distinct(reuse)) fail("reuse should not be distinct");

    const arrowNocap = [];
    for (let i = 0; i < K; i++) arrowNocap.push((x) => x + 1);
    if (!distinct(arrowNocap)) fail("arrow_nocap not distinct");
    if (arrowNocap[0](1) !== 2) fail("arrow_nocap value");

    const fnexprNocap = [];
    for (let i = 0; i < K; i++) fnexprNocap.push(function (x) { return x + 1; });
    if (!distinct(fnexprNocap)) fail("fnexpr_nocap not distinct");
    if (fnexprNocap[0](1) !== 2) fail("fnexpr_nocap value");

    const arrowCap1 = [];
    for (let i = 0; i < K; i++) arrowCap1.push((x) => x + k0);
    if (!distinct(arrowCap1)) fail("arrow_cap1 not distinct");
    if (arrowCap1[K - 1](10) !== 11) fail("arrow_cap1 value");

    const fnexprCap1 = [];
    for (let i = 0; i < K; i++) fnexprCap1.push(function (x) { return x + k0; });
    if (!distinct(fnexprCap1)) fail("fnexpr_cap1 not distinct");
    if (fnexprCap1[K - 1](10) !== 11) fail("fnexpr_cap1 value");

    const arrowCap4 = [];
    for (let i = 0; i < K; i++) arrowCap4.push((x) => x + k0 + k1 + k2 + k3);
    if (!distinct(arrowCap4)) fail("arrow_cap4 not distinct");
    if (arrowCap4[K - 1](10) !== 20) fail("arrow_cap4 value");

    // The per-iteration binding must be observed per iteration, which is what
    // makes this shape semantically heavier.
    const loopbind = [];
    for (let i = 0; i < K; i++) loopbind.push(() => i);
    if (!distinct(loopbind)) fail("arrow_loopbind not distinct");
    for (let i = 0; i < K; i++) if (loopbind[i]() !== i) fail("arrow_loopbind binding");

    // create-and-call: the immediately-called closure is still a fresh object.
    const created = [];
    let acc = 0;
    for (let i = 0; i < K; i++) {
        const g = (x) => x + 1;
        acc += g(1);
        created.push(g);
    }
    if (!distinct(created)) fail("arrow_call not distinct");
    if (acc !== 2 * K) fail("arrow_call accumulator");

    // Function objects created by distinct evaluations of the same source
    // position must also have independent own properties.
    const a = (x) => x + 1;
    const b = (x) => x + 1;
    a.tag = 1;
    if (Object.prototype.hasOwnProperty.call(b, "tag")) fail("own property bleed");
    if (a.prototype !== undefined) fail("arrow has no prototype");
    const fa = function (x) { return x + 1; };
    const fb = function (x) { return x + 1; };
    if (fa.prototype === fb.prototype) fail("function prototype shared");

    return calls * 1000000 + acc;
}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cases-dir", default=DEFAULT_CASES)
    parser.add_argument("--iterations", type=int, default=N_DEFAULT,
                        help="inner loop count N baked into each case")
    parser.add_argument("--prefix", default="closure_")
    parser.add_argument("--only-counts", action="store_true",
                        help="emit only the small-N variants used by the gdb "
                             "dynamic counter")
    args = parser.parse_args()

    os.makedirs(args.cases_dir, exist_ok=True)
    written = []
    for name in ORDER:
        shape = SHAPES[name]
        for lifetime, builder in (("churn", churn_case), ("retain", retain_case)):
            if lifetime == "retain" and shape.get("churn_only"):
                continue
            path = os.path.join(
                args.cases_dir, "%s%s_%s.js" % (args.prefix, name, lifetime)
            )
            with open(path, "w") as handle:
                handle.write(builder(name, shape, args.iterations))
            written.append(path)

    probe = os.path.join(args.cases_dir, "%sidentity_probe.js" % args.prefix)
    with open(probe, "w") as handle:
        handle.write(IDENTITY_PROBE)
    written.append(probe)

    for path in written:
        print(path)


if __name__ == "__main__":
    main()
