// Generated by tools/perf/typedarray/gen_cases.py for audit line P7-30.
// Every case wraps its loop in a function so the loop variable is a local slot
// on both engines; a top-level `let` loop is a known zjs-only slow path and
// would contaminate the stage attribution.
// Plain user-class construction control: the generic construct path with no typed-array work.
class C {
    constructor(x) {
        this.x = x;
    }
}
function work(n) {
    let sink = 0;
    for (let i = 0; i < n; i++) {
        const o = new C(i);
        sink += o.x & 255;
    }
    return sink;
}
print(work(200000));
