// Generated by tools/perf/typedarray/gen_cases.py for audit line P7-30.
// Every case wraps its loop in a function so the loop variable is a local slot
// on both engines; a top-level `let` loop is a known zjs-only slow path and
// would contaminate the stage attribution.
// Loop-overhead control: the same loop and the same sink update, no allocation.
function work(n) {
    let sink = 0;
    for (let i = 0; i < n; i++) {
        sink += i & 255;
    }
    return sink;
}
print(work(200000));
