// Generated by tools/perf/typedarray/gen_cases.py for audit line P7-30.
// Every case wraps its loop in a function so the loop variable is a local slot
// on both engines; a top-level `let` loop is a known zjs-only slow path and
// would contaminate the stage attribution.
// ta40 with a resident population so the slab cannot churn.
// Resident population that keeps every size class this workload touches
// off its empty boundary, so the slab never churns an arena. The count is
// deliberately not a multiple of blocks-per-arena (P7-00 trap), and was swept
// until both engines read ~0 arena events per operation, not just zjs.
const keep = [];
for (let i = 0; i < 440; i++) keep.push(new Uint8Array(40));
function work(n) {
    let sink = 0;
    for (let i = 0; i < n; i++) {
        const b = new Uint8Array(40);
        b[0] = i & 255;
        sink += b[0];
    }
    return sink;
}
print(work(200000));
