// Generated by tools/perf/typedarray/gen_cases.py for audit line P7-30.
// Every case wraps its loop in a function so the loop variable is a local slot
// on both engines; a top-level `let` loop is a known zjs-only slow path and
// would contaminate the stage attribution.
// TypedArray wrapper + view metadata only: the buffer and its bytes already exist.
const buf = new ArrayBuffer(64);
function work(n) {
    let sink = 0;
    for (let i = 0; i < n; i++) {
        const b = new Uint8Array(buf);
        b[0] = i & 255;
        sink += b[0];
    }
    return sink;
}
print(work(200000));
