// Generated by tools/gen_irregexp_bytecode_layout.py. Do not edit by hand.
// Packing matches vendor/irregexp/imported/regexp-bytecodes-inl.h.
const std = @import("std");

pub const table_size: usize = 16;
pub const table_mask: u32 = 0x7f;
pub const bytecode_alignment: usize = 4;

pub const Opcode = enum(u8) {
    break_ = 0,
    push_current_position = 1,
    push_backtrack = 2,
    write_current_position_to_register = 3,
    read_current_position_from_register = 4,
    write_stack_pointer_to_register = 5,
    read_stack_pointer_from_register = 6,
    set_register = 7,
    clear_registers = 8,
    advance_register = 9,
    pop_current_position = 10,
    push_register = 11,
    pop_register = 12,
    fail = 13,
    succeed = 14,
    advance_current_position = 15,
    go_to = 16,
    load_current_character = 17,
    check_position = 18,
    check_special_class_ranges = 19,
    check_character = 20,
    check_not_character = 21,
    check_character_after_and = 22,
    check_not_character_after_and = 23,
    check_not_character_after_minus_and = 24,
    check_character_in_range = 25,
    check_character_not_in_range = 26,
    check_character_lt = 27,
    check_character_gt = 28,
    if_register_lt = 29,
    if_register_ge = 30,
    if_register_eq_pos = 31,
    check_at_start = 32,
    check_not_at_start = 33,
    check_fixed_length_loop = 34,
    set_current_position_from_end = 35,
    backtrack = 36,
    load_current_character_unchecked = 37,
    check_bit_in_table = 38,
    load2_current_chars = 39,
    load2_current_chars_unchecked = 40,
    load4_current_chars = 41,
    load4_current_chars_unchecked = 42,
    check4_chars = 43,
    check_not4_chars = 44,
    and_check4_chars = 45,
    and_check_not4_chars = 46,
    advance_cp_and_goto = 47,
    check_not_back_ref = 48,
    check_not_back_ref_no_case = 49,
    check_not_back_ref_no_case_unicode = 50,
    check_not_back_ref_backward = 51,
    check_not_back_ref_no_case_backward = 52,
    check_not_back_ref_no_case_unicode_backward = 53,
    skip_until_bit_in_table = 54,
    skip_until_char_and = 55,
    skip_until_char = 56,
    skip_until_char_or_char = 57,
    skip_until_gt_or_not_bit_in_table = 58,
    skip_until_one_of_masked = 59,
    skip_until_one_of_masked3 = 60,
};

pub const opcode_count: usize = 61;

pub const opcode_size: [opcode_count]u8 = .{
    4, // Break / break_
    4, // PushCurrentPosition / push_current_position
    8, // PushBacktrack / push_backtrack
    8, // WriteCurrentPositionToRegister / write_current_position_to_register
    4, // ReadCurrentPositionFromRegister / read_current_position_from_register
    4, // WriteStackPointerToRegister / write_stack_pointer_to_register
    4, // ReadStackPointerFromRegister / read_stack_pointer_from_register
    8, // SetRegister / set_register
    8, // ClearRegisters / clear_registers
    8, // AdvanceRegister / advance_register
    4, // PopCurrentPosition / pop_current_position
    8, // PushRegister / push_register
    4, // PopRegister / pop_register
    4, // Fail / fail
    4, // Succeed / succeed
    4, // AdvanceCurrentPosition / advance_current_position
    8, // GoTo / go_to
    12, // LoadCurrentCharacter / load_current_character
    8, // CheckPosition / check_position
    8, // CheckSpecialClassRanges / check_special_class_ranges
    8, // CheckCharacter / check_character
    8, // CheckNotCharacter / check_not_character
    12, // CheckCharacterAfterAnd / check_character_after_and
    12, // CheckNotCharacterAfterAnd / check_not_character_after_and
    12, // CheckNotCharacterAfterMinusAnd / check_not_character_after_minus_and
    12, // CheckCharacterInRange / check_character_in_range
    12, // CheckCharacterNotInRange / check_character_not_in_range
    8, // CheckCharacterLT / check_character_lt
    8, // CheckCharacterGT / check_character_gt
    12, // IfRegisterLT / if_register_lt
    12, // IfRegisterGE / if_register_ge
    8, // IfRegisterEqPos / if_register_eq_pos
    8, // CheckAtStart / check_at_start
    8, // CheckNotAtStart / check_not_at_start
    8, // CheckFixedLengthLoop / check_fixed_length_loop
    4, // SetCurrentPositionFromEnd / set_current_position_from_end
    4, // Backtrack / backtrack
    4, // LoadCurrentCharacterUnchecked / load_current_character_unchecked
    24, // CheckBitInTable / check_bit_in_table
    12, // Load2CurrentChars / load2_current_chars
    4, // Load2CurrentCharsUnchecked / load2_current_chars_unchecked
    12, // Load4CurrentChars / load4_current_chars
    4, // Load4CurrentCharsUnchecked / load4_current_chars_unchecked
    12, // Check4Chars / check4_chars
    12, // CheckNot4Chars / check_not4_chars
    16, // AndCheck4Chars / and_check4_chars
    16, // AndCheckNot4Chars / and_check_not4_chars
    8, // AdvanceCpAndGoto / advance_cp_and_goto
    8, // CheckNotBackRef / check_not_back_ref
    8, // CheckNotBackRefNoCase / check_not_back_ref_no_case
    8, // CheckNotBackRefNoCaseUnicode / check_not_back_ref_no_case_unicode
    8, // CheckNotBackRefBackward / check_not_back_ref_backward
    8, // CheckNotBackRefNoCaseBackward / check_not_back_ref_no_case_backward
    8, // CheckNotBackRefNoCaseUnicodeBackward / check_not_back_ref_no_case_unicode_backward
    36, // SkipUntilBitInTable / skip_until_bit_in_table
    24, // SkipUntilCharAnd / skip_until_char_and
    20, // SkipUntilChar / skip_until_char
    24, // SkipUntilCharOrChar / skip_until_char_or_char
    36, // SkipUntilGtOrNotBitInTable / skip_until_gt_or_not_bit_in_table
    48, // SkipUntilOneOfMasked / skip_until_one_of_masked
    92, // SkipUntilOneOfMasked3 / skip_until_one_of_masked3
};

pub fn sizeOf(op: Opcode) u32 {
    return opcode_size[@intFromEnum(op)];
}

pub const Off = struct {
    pub const push_backtrack = struct {
        pub const label: usize = 4; // JumpTarget as u32
    };
    pub const write_current_position_to_register = struct {
        pub const register_index: usize = 2; // Register as u16
        pub const cp_offset: usize = 4; // Offset as i16
    };
    pub const read_current_position_from_register = struct {
        pub const register_index: usize = 2; // Register as u16
    };
    pub const write_stack_pointer_to_register = struct {
        pub const register_index: usize = 2; // Register as u16
    };
    pub const read_stack_pointer_from_register = struct {
        pub const register_index: usize = 2; // Register as u16
    };
    pub const set_register = struct {
        pub const register_index: usize = 2; // Register as u16
        pub const value: usize = 4; // Int32 as i32
    };
    pub const clear_registers = struct {
        pub const from_register: usize = 2; // Register as u16
        pub const to_register: usize = 4; // Register as u16
    };
    pub const advance_register = struct {
        pub const register_index: usize = 2; // Register as u16
        pub const by: usize = 4; // Offset as i16
    };
    pub const push_register = struct {
        pub const register_index: usize = 2; // Register as u16
        pub const stack_check: usize = 4; // StackCheckFlag as u8
    };
    pub const pop_register = struct {
        pub const register_index: usize = 2; // Register as u16
    };
    pub const advance_current_position = struct {
        pub const by: usize = 2; // Offset as i16
    };
    pub const go_to = struct {
        pub const label: usize = 4; // JumpTarget as u32
    };
    pub const load_current_character = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const bounds_check_offset: usize = 4; // BoundsCheckOffset as i32
        pub const on_failure: usize = 8; // JumpTarget as u32
    };
    pub const check_position = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const on_failure: usize = 4; // JumpTarget as u32
    };
    pub const check_special_class_ranges = struct {
        pub const character_set: usize = 1; // StandardCharacterSet as u8
        pub const on_no_match: usize = 4; // JumpTarget as u32
    };
    pub const check_character = struct {
        pub const character: usize = 2; // Char as u16
        pub const on_equal: usize = 4; // JumpTarget as u32
    };
    pub const check_not_character = struct {
        pub const character: usize = 2; // Char as u16
        pub const on_not_equal: usize = 4; // JumpTarget as u32
    };
    pub const check_character_after_and = struct {
        pub const character: usize = 2; // Char as u16
        pub const mask: usize = 4; // Uint32 as u32
        pub const on_equal: usize = 8; // JumpTarget as u32
    };
    pub const check_not_character_after_and = struct {
        pub const character: usize = 2; // Char as u16
        pub const mask: usize = 4; // Uint32 as u32
        pub const on_not_equal: usize = 8; // JumpTarget as u32
    };
    pub const check_not_character_after_minus_and = struct {
        pub const character: usize = 2; // Char as u16
        pub const minus: usize = 4; // Char as u16
        pub const mask: usize = 6; // Char as u16
        pub const on_not_equal: usize = 8; // JumpTarget as u32
    };
    pub const check_character_in_range = struct {
        pub const from: usize = 2; // Char as u16
        pub const to: usize = 4; // Char as u16
        pub const on_in_range: usize = 8; // JumpTarget as u32
    };
    pub const check_character_not_in_range = struct {
        pub const from: usize = 2; // Char as u16
        pub const to: usize = 4; // Char as u16
        pub const on_not_in_range: usize = 8; // JumpTarget as u32
    };
    pub const check_character_lt = struct {
        pub const limit: usize = 2; // Char as u16
        pub const on_less: usize = 4; // JumpTarget as u32
    };
    pub const check_character_gt = struct {
        pub const limit: usize = 2; // Char as u16
        pub const on_greater: usize = 4; // JumpTarget as u32
    };
    pub const if_register_lt = struct {
        pub const register_index: usize = 2; // Register as u16
        pub const comparand: usize = 4; // Int32 as i32
        pub const on_less_than: usize = 8; // JumpTarget as u32
    };
    pub const if_register_ge = struct {
        pub const register_index: usize = 2; // Register as u16
        pub const comparand: usize = 4; // Int32 as i32
        pub const on_greater_or_equal: usize = 8; // JumpTarget as u32
    };
    pub const if_register_eq_pos = struct {
        pub const register_index: usize = 2; // Register as u16
        pub const on_eq: usize = 4; // JumpTarget as u32
    };
    pub const check_at_start = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const on_at_start: usize = 4; // JumpTarget as u32
    };
    pub const check_not_at_start = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const on_not_at_start: usize = 4; // JumpTarget as u32
    };
    pub const check_fixed_length_loop = struct {
        pub const on_tos_equals_current_position: usize = 4; // JumpTarget as u32
    };
    pub const set_current_position_from_end = struct {
        pub const by: usize = 2; // Offset as i16
    };
    pub const backtrack = struct {
        pub const return_code: usize = 2; // Int16 as i16
    };
    pub const load_current_character_unchecked = struct {
        pub const cp_offset: usize = 2; // Offset as i16
    };
    pub const check_bit_in_table = struct {
        pub const on_bit_set: usize = 4; // JumpTarget as u32
        pub const table: usize = 8; // BitTable as table
    };
    pub const load2_current_chars = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const bounds_check_offset: usize = 4; // BoundsCheckOffset as i32
        pub const on_failure: usize = 8; // JumpTarget as u32
    };
    pub const load2_current_chars_unchecked = struct {
        pub const cp_offset: usize = 2; // Offset as i16
    };
    pub const load4_current_chars = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const bounds_check_offset: usize = 4; // BoundsCheckOffset as i32
        pub const on_failure: usize = 8; // JumpTarget as u32
    };
    pub const load4_current_chars_unchecked = struct {
        pub const cp_offset: usize = 2; // Offset as i16
    };
    pub const check4_chars = struct {
        pub const characters: usize = 4; // Uint32 as u32
        pub const on_equal: usize = 8; // JumpTarget as u32
    };
    pub const check_not4_chars = struct {
        pub const characters: usize = 4; // Uint32 as u32
        pub const on_not_equal: usize = 8; // JumpTarget as u32
    };
    pub const and_check4_chars = struct {
        pub const characters: usize = 4; // Uint32 as u32
        pub const mask: usize = 8; // Uint32 as u32
        pub const on_equal: usize = 12; // JumpTarget as u32
    };
    pub const and_check_not4_chars = struct {
        pub const characters: usize = 4; // Uint32 as u32
        pub const mask: usize = 8; // Uint32 as u32
        pub const on_not_equal: usize = 12; // JumpTarget as u32
    };
    pub const advance_cp_and_goto = struct {
        pub const by: usize = 2; // Offset as i16
        pub const on_goto: usize = 4; // JumpTarget as u32
    };
    pub const check_not_back_ref = struct {
        pub const start_reg: usize = 2; // Register as u16
        pub const on_not_equal: usize = 4; // JumpTarget as u32
    };
    pub const check_not_back_ref_no_case = struct {
        pub const start_reg: usize = 2; // Register as u16
        pub const on_not_equal: usize = 4; // JumpTarget as u32
    };
    pub const check_not_back_ref_no_case_unicode = struct {
        pub const start_reg: usize = 2; // Register as u16
        pub const on_not_equal: usize = 4; // JumpTarget as u32
    };
    pub const check_not_back_ref_backward = struct {
        pub const start_reg: usize = 2; // Register as u16
        pub const on_not_equal: usize = 4; // JumpTarget as u32
    };
    pub const check_not_back_ref_no_case_backward = struct {
        pub const start_reg: usize = 2; // Register as u16
        pub const on_not_equal: usize = 4; // JumpTarget as u32
    };
    pub const check_not_back_ref_no_case_unicode_backward = struct {
        pub const start_reg: usize = 2; // Register as u16
        pub const on_not_equal: usize = 4; // JumpTarget as u32
    };
    pub const skip_until_bit_in_table = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const advance_by: usize = 4; // Offset as i16
        pub const table: usize = 8; // BitTable as table
        pub const bounds_check_offset: usize = 24; // BoundsCheckOffset as i32
        pub const on_match: usize = 28; // JumpTarget as u32
        pub const on_no_match: usize = 32; // JumpTarget as u32
    };
    pub const skip_until_char_and = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const advance_by: usize = 4; // Offset as i16
        pub const character: usize = 6; // Char as u16
        pub const mask: usize = 8; // Uint32 as u32
        pub const bounds_check_offset: usize = 12; // BoundsCheckOffset as i32
        pub const on_match: usize = 16; // JumpTarget as u32
        pub const on_no_match: usize = 20; // JumpTarget as u32
    };
    pub const skip_until_char = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const advance_by: usize = 4; // Offset as i16
        pub const character: usize = 6; // Char as u16
        pub const bounds_check_offset: usize = 8; // BoundsCheckOffset as i32
        pub const on_match: usize = 12; // JumpTarget as u32
        pub const on_no_match: usize = 16; // JumpTarget as u32
    };
    pub const skip_until_char_or_char = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const advance_by: usize = 4; // Offset as i16
        pub const char1: usize = 6; // Char as u16
        pub const char2: usize = 8; // Char as u16
        pub const bounds_check_offset: usize = 12; // BoundsCheckOffset as i32
        pub const on_match: usize = 16; // JumpTarget as u32
        pub const on_no_match: usize = 20; // JumpTarget as u32
    };
    pub const skip_until_gt_or_not_bit_in_table = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const advance_by: usize = 4; // Offset as i16
        pub const character: usize = 6; // Char as u16
        pub const table: usize = 8; // BitTable as table
        pub const bounds_check_offset: usize = 24; // BoundsCheckOffset as i32
        pub const on_match: usize = 28; // JumpTarget as u32
        pub const on_no_match: usize = 32; // JumpTarget as u32
    };
    pub const skip_until_one_of_masked = struct {
        pub const cp_offset: usize = 2; // Offset as i16
        pub const advance_by: usize = 4; // Offset as i16
        pub const both_chars: usize = 8; // Uint32 as u32
        pub const both_mask: usize = 12; // Uint32 as u32
        pub const max_offset: usize = 16; // BoundsCheckOffset as i32
        pub const chars1: usize = 20; // Uint32 as u32
        pub const mask1: usize = 24; // Uint32 as u32
        pub const chars2: usize = 28; // Uint32 as u32
        pub const mask2: usize = 32; // Uint32 as u32
        pub const on_match1: usize = 36; // JumpTarget as u32
        pub const on_match2: usize = 40; // JumpTarget as u32
        pub const on_failure: usize = 44; // JumpTarget as u32
    };
    pub const skip_until_one_of_masked3 = struct {
        pub const bc0_cp_offset: usize = 2; // Offset as i16
        pub const bc0_advance_by: usize = 4; // Offset as i16
        pub const bc0_table: usize = 8; // BitTable as table
        pub const bc1_bounds_check_offset: usize = 24; // BoundsCheckOffset as i32
        pub const bc1_on_failure: usize = 28; // JumpTarget as u32
        pub const bc1_cp_offset: usize = 32; // Offset as i16
        pub const bc2_characters: usize = 36; // Uint32 as u32
        pub const bc2_mask: usize = 40; // Uint32 as u32
        pub const bc3_by: usize = 44; // Offset as i16
        pub const bc4_bounds_check_offset: usize = 48; // BoundsCheckOffset as i32
        pub const bc4_cp_offset: usize = 52; // Offset as i16
        pub const bc5_characters: usize = 56; // Uint32 as u32
        pub const bc5_mask: usize = 60; // Uint32 as u32
        pub const bc5_on_equal: usize = 64; // JumpTarget as u32
        pub const bc6_characters: usize = 68; // Uint32 as u32
        pub const bc6_mask: usize = 72; // Uint32 as u32
        pub const bc6_on_equal: usize = 76; // JumpTarget as u32
        pub const bc7_characters: usize = 80; // Uint32 as u32
        pub const bc7_mask: usize = 84; // Uint32 as u32
        pub const fallthrough_jump_target: usize = 88; // JumpTarget as u32
    };
};

test "Irregexp bytecode sizes are 4-byte aligned" {
    for (opcode_size) |sz| {
        try std.testing.expect(sz % 4 == 0);
        try std.testing.expect(sz >= 4);
    }
}

