// P7-50 closure-allocation probe, not a policy sentinel (see
// tools/perf/same_runtime/cases/README.md). Generated by
// tools/perf/closure_alloc/gen_cases.py -- edit the generator, not this
// file.
// arrow-no-capture: non-capturing arrow created every iteration
// lifetime retain: odd run() calls fill N already-null
// preallocated slots (N creations, no release); even run() calls
// clear them (N releases, no creation). The harness times one run()
// call per sample, so with an even --warmup the odd-indexed samples
// are creation-only and the even-indexed samples are release-only.
const N = 20000;
const slots = new Array(N);
for (let i = 0; i < N; i++) slots[i] = null;
let calls = 0;
let acc = 0;
function run() {
    calls += 1;
    acc = 0;
    if ((calls & 1) === 1) {
        for (let i = 0; i < N; i++) {
            slots[i] = (x) => x + 1;
        }
        return calls * 1000000 + acc * 1000 + slots[N - 1](1);
    }
    for (let i = 0; i < N; i++) slots[i] = null;
    return calls * 1000000;
}
print(run());
