// P7-50 closure-allocation probe, not a policy sentinel (see
// tools/perf/same_runtime/cases/README.md). Generated by
// tools/perf/closure_alloc/gen_cases.py -- edit the generator, not this
// file.
// P7-40 cross-check: identifier assignment target, so the arrow is subject to NamedEvaluation and pays a second name define
// lifetime churn: one slot overwritten per iteration, so each
// iteration is one creation plus the previous closure's release.
// Assignment target: g (see generator header on NamedEvaluation).
const N = 20000;
let g = null;
let calls = 0;
let acc = 0;
function run() {
    calls += 1;
    acc = 0;
    for (let i = 0; i < N; i++) {
        g = (x) => x + 1;
    }
    return calls * 1000000 + acc * 1000 + g(1);
}
print(run());
