// P7-50 closure-allocation probe, not a policy sentinel (see
// tools/perf/same_runtime/cases/README.md). Generated by
// tools/perf/closure_alloc/gen_cases.py -- edit the generator, not this
// file.
// P7-50 semantic probe. The perf cases checksum only one closure, so an
// engine that hoisted the loop-body function expression out of the loop, or
// cached and reused one function object, would silently look fast. This probe
// runs in the SAME layer (retained callable, source compiled once) and proves
// that every evaluation of each shape produces a DISTINCT Function identity,
// and that each capturing shape observes the value it is supposed to observe.
//
// run() throws on any violation, which the harness reports as a fatal engine
// error, so a passing perf run of this case is the proof.
const K = 64;

function distinct(list) {
    for (let i = 0; i < list.length; i++) {
        if (typeof list[i] !== "function") return false;
        for (let j = i + 1; j < list.length; j++) {
            if (list[i] === list[j]) return false;
        }
    }
    return true;
}

function fail(what) {
    throw new Error("P7-50 identity probe failed: " + what);
}

let calls = 0;

function run() {
    calls += 1;
    const k0 = 1, k1 = 2, k2 = 3, k3 = 4;

    // reuse-precreated is the one shape that MUST be identical every time.
    const F = (x) => x + 1;
    const reuse = [];
    for (let i = 0; i < K; i++) reuse.push(F);
    for (let i = 0; i < K; i++) if (reuse[i] !== F) fail("reuse identity");
    if (distinct(reuse)) fail("reuse should not be distinct");

    const arrowNocap = [];
    for (let i = 0; i < K; i++) arrowNocap.push((x) => x + 1);
    if (!distinct(arrowNocap)) fail("arrow_nocap not distinct");
    if (arrowNocap[0](1) !== 2) fail("arrow_nocap value");

    const fnexprNocap = [];
    for (let i = 0; i < K; i++) fnexprNocap.push(function (x) { return x + 1; });
    if (!distinct(fnexprNocap)) fail("fnexpr_nocap not distinct");
    if (fnexprNocap[0](1) !== 2) fail("fnexpr_nocap value");

    const arrowCap1 = [];
    for (let i = 0; i < K; i++) arrowCap1.push((x) => x + k0);
    if (!distinct(arrowCap1)) fail("arrow_cap1 not distinct");
    if (arrowCap1[K - 1](10) !== 11) fail("arrow_cap1 value");

    const fnexprCap1 = [];
    for (let i = 0; i < K; i++) fnexprCap1.push(function (x) { return x + k0; });
    if (!distinct(fnexprCap1)) fail("fnexpr_cap1 not distinct");
    if (fnexprCap1[K - 1](10) !== 11) fail("fnexpr_cap1 value");

    const arrowCap4 = [];
    for (let i = 0; i < K; i++) arrowCap4.push((x) => x + k0 + k1 + k2 + k3);
    if (!distinct(arrowCap4)) fail("arrow_cap4 not distinct");
    if (arrowCap4[K - 1](10) !== 20) fail("arrow_cap4 value");

    // The per-iteration binding must be observed per iteration, which is what
    // makes this shape semantically heavier.
    const loopbind = [];
    for (let i = 0; i < K; i++) loopbind.push(() => i);
    if (!distinct(loopbind)) fail("arrow_loopbind not distinct");
    for (let i = 0; i < K; i++) if (loopbind[i]() !== i) fail("arrow_loopbind binding");

    // create-and-call: the immediately-called closure is still a fresh object.
    const created = [];
    let acc = 0;
    for (let i = 0; i < K; i++) {
        const g = (x) => x + 1;
        acc += g(1);
        created.push(g);
    }
    if (!distinct(created)) fail("arrow_call not distinct");
    if (acc !== 2 * K) fail("arrow_call accumulator");

    // Function objects created by distinct evaluations of the same source
    // position must also have independent own properties.
    const a = (x) => x + 1;
    const b = (x) => x + 1;
    a.tag = 1;
    if (Object.prototype.hasOwnProperty.call(b, "tag")) fail("own property bleed");
    if (a.prototype !== undefined) fail("arrow has no prototype");
    const fa = function (x) { return x + 1; };
    const fb = function (x) { return x + 1; };
    if (fa.prototype === fb.prototype) fail("function prototype shared");

    return calls * 1000000 + acc;
}
print(run());
