//! The engine's error-set authority.
//!
//! `RuntimeError` is every failure the engine itself can raise. `HostError` is
//! the historical transport name for that same set: producer-specific I/O is
//! converted to JavaScript errors before reaching it. Both live in core because
//! core-level callback surfaces need them and core cannot import exec.
//! `exec.exceptions` re-exports them under their historical names.

pub const RuntimeError = error{
    AccessorWithoutSetter,
    AmbiguousExport,
    AwaitOutsideAsyncFunction,
    BigIntTooLarge,
    BytecodeCorrupt,
    BytecodeOverflow,
    ClosureVarNotFound,
    CodepointTooLarge,
    DivisionByZero,
    DuplicateClass,
    DualCompileMismatch,
    DerivedConstructorReturn,
    DerivedThisUninitialized,
    EvalError,
    IncompatibleDescriptor,
    Interrupted,
    InvalidAssignmentTarget,
    InvalidAtom,
    InvalidBytecode,
    InvalidBuiltinRegistry,
    InvalidCharacter,
    InvalidCharacterError,
    InvalidClassId,
    InvalidEscape,
    InvalidIdentifier,
    InvalidLength,
    InvalidLhs,
    InvalidNumber,
    InvalidNumberLiteral,
    InvalidOpcode,
    InvalidPattern,
    InvalidPrivateName,
    InvalidRadix,
    InvalidRegExp,
    InvalidUnicodeEscape,
    InvalidUtf8,
    LegacyOctalInStrictMode,
    MissingExport,
    ModuleLinkFailed,
    ModuleNotFound,
    NegativeExponent,
    NotExtensible,
    NotRegExpLiteral,
    OutOfMemory,
    Overflow,
    ParserInvariant,
    Pc2LineOverflow,
    Pc2LineTruncated,
    ProcessExit,
    PrototypeCycle,
    RangeError,
    ReadOnly,
    ReferenceError,
    StackMismatch,
    StackOverflow,
    StackUnderflow,
    StringTooLong,
    SyntaxError,
    SystemError,
    JSException,
    Timeout,
    TooManyJobArgs,
    TypeError,
    URIError,
    UnhandledPromiseRejection,
    UnterminatedComment,
    UnterminatedRegExp,
    UnterminatedString,
    UnterminatedTemplate,
    UnexpectedEof,
    UnexpectedToken,
    UnsupportedSimpleJson,
    Utf8CannotEncodeSurrogateHalf,
    Utf8EncodesSurrogateHalf,
    YieldOutsideGenerator,
    HtmlCommentInModule,
};

pub const HostError = RuntimeError;
