// P7-50 closure-allocation probe, not a policy sentinel (see
// tools/perf/same_runtime/cases/README.md). Generated by
// tools/perf/closure_alloc/gen_cases.py -- edit the generator, not this
// file.
// arrow-capture-4: captures four already-existing outer locals, for the closure-slot slope
// lifetime churn: one slot overwritten per iteration, so each
// iteration is one creation plus the previous closure's release.
// Assignment target: slot[0] (see generator header on NamedEvaluation).
const N = 20000;
const slot = [null];
let calls = 0;
let acc = 0;
function run() {
    const k0 = 1;
    const k1 = 2;
    const k2 = 3;
    const k3 = 4;
    calls += 1;
    acc = 0;
    for (let i = 0; i < N; i++) {
        slot[0] = (x) => x + k0 + k1 + k2 + k3;
    }
    return calls * 1000000 + acc * 1000 + slot[0](1);
}
