#!/usr/bin/env node
// Generates src/libs/emoji_sequences.zig from the Unicode emoji sequence data
// files (UTS #51):
//   https://unicode.org/Public/emoji/latest/emoji-sequences.txt
//   https://unicode.org/Public/emoji/latest/emoji-zwj-sequences.txt
//
// Usage:
//   node tools/gen_emoji_sequences.js <emoji-sequences.txt> <emoji-zwj-sequences.txt> > src/libs/emoji_sequences.zig

'use strict';

const fs = require('fs');

if (process.argv.length !== 4) {
  console.error('usage: gen_emoji_sequences.js <emoji-sequences.txt> <emoji-zwj-sequences.txt>');
  process.exit(1);
}

const ranges = []; // Basic_Emoji single code points, as inclusive [lo, hi] ranges.
const sequences = {
  Basic_Emoji: [],
  Emoji_Keycap_Sequence: [],
  RGI_Emoji_Flag_Sequence: [],
  RGI_Emoji_Tag_Sequence: [],
  RGI_Emoji_Modifier_Sequence: [],
  RGI_Emoji_ZWJ_Sequence: [],
};
let version = null;

function parseFile(path) {
  for (const rawLine of fs.readFileSync(path, 'utf8').split('\n')) {
    const versionMatch = rawLine.match(/^# Version: (.+)$/);
    if (versionMatch) version = versionMatch[1].trim();
    const line = rawLine.split('#')[0].trim();
    if (line.length === 0) continue;
    const fields = line.split(';').map((field) => field.trim());
    if (fields.length < 2) throw new Error(`bad line: ${rawLine}`);
    const [codePointsField, typeField] = fields;
    const list = sequences[typeField];
    if (list === undefined) throw new Error(`unknown type_field: ${typeField}`);
    const rangeMatch = codePointsField.match(/^([0-9A-F]+)\.\.([0-9A-F]+)$/);
    if (rangeMatch) {
      if (typeField !== 'Basic_Emoji') throw new Error(`unexpected range: ${rawLine}`);
      ranges.push([parseInt(rangeMatch[1], 16), parseInt(rangeMatch[2], 16)]);
      continue;
    }
    const codePoints = codePointsField.split(/\s+/).map((hex) => parseInt(hex, 16));
    if (codePoints.some(Number.isNaN)) throw new Error(`bad code points: ${rawLine}`);
    if (codePoints.length === 1) {
      if (typeField !== 'Basic_Emoji') throw new Error(`unexpected single code point: ${rawLine}`);
      ranges.push([codePoints[0], codePoints[0]]);
      continue;
    }
    list.push(codePoints);
  }
}

parseFile(process.argv[2]);
parseFile(process.argv[3]);

// Merge adjacent/overlapping single-code-point ranges.
ranges.sort((a, b) => a[0] - b[0]);
const merged = [];
for (const [lo, hi] of ranges) {
  const last = merged[merged.length - 1];
  if (last !== undefined && lo <= last[1] + 1) {
    last[1] = Math.max(last[1], hi);
  } else {
    merged.push([lo, hi]);
  }
}

function hex(codePoint) {
  return '0x' + codePoint.toString(16).padStart(4, '0');
}

function emitSequences(name, doc, list) {
  const lines = list.map((seq) => `    &.{ ${seq.map(hex).join(', ')} },`);
  return `${doc}pub const ${name} = [_][]const u21{\n${lines.join('\n')}\n};\n`;
}

let out = '';
out += '// RGI emoji sequence data (UTS #51) for RegExp v-mode properties of strings.\n';
out += '// Generated by tools/gen_emoji_sequences.js from the Unicode data files\n';
out += '//   https://unicode.org/Public/emoji/latest/emoji-sequences.txt\n';
out += '//   https://unicode.org/Public/emoji/latest/emoji-zwj-sequences.txt\n';
out += `// Emoji version: ${version}\n`;
out += '// Do not edit by hand; rerun the generator instead.\n';
out += '\n';
out += 'pub const CodePointRange = struct { lo: u21, hi: u21 };\n';
out += '\n';
out += '/// Basic_Emoji entries that are a single code point (inclusive ranges).\n';
out += 'pub const basic_emoji_ranges = [_]CodePointRange{\n';
out += merged.map(([lo, hi]) => `    .{ .lo = ${hex(lo)}, .hi = ${hex(hi)} },`).join('\n');
out += '\n};\n\n';
out += emitSequences(
  'basic_emoji_sequences',
  '/// Basic_Emoji entries that are emoji presentation sequences (code point + U+FE0F).\n',
  sequences.Basic_Emoji,
);
out += '\n';
out += emitSequences('emoji_keycap_sequences', '', sequences.Emoji_Keycap_Sequence);
out += '\n';
out += emitSequences('rgi_emoji_flag_sequences', '', sequences.RGI_Emoji_Flag_Sequence);
out += '\n';
out += emitSequences('rgi_emoji_tag_sequences', '', sequences.RGI_Emoji_Tag_Sequence);
out += '\n';
out += emitSequences('rgi_emoji_modifier_sequences', '', sequences.RGI_Emoji_Modifier_Sequence);
out += '\n';
out += emitSequences('rgi_emoji_zwj_sequences', '', sequences.RGI_Emoji_ZWJ_Sequence);

process.stdout.write(out);
