#!/usr/bin/env python3
"""Generate the P7-30 stage-decomposition case matrix.

`new Uint8Array(64)` is split into stages that can be switched on and off from
JS alone, so that no engine source has to change to attribute the cost:

  noop      loop and sink update only
  ta{k}     full construction: view wrapper + buffer wrapper + backing bytes +
            zero fill + GC registration, at four sizes that straddle the
            32-byte inline-storage boundary
  ab{k}     buffer wrapper + backing bytes + zero fill, no view
  taview    view wrapper + view metadata only, over a pre-existing buffer
  tafill    zero fill only, over a pre-existing view, zero allocation
  classnew  the generic construct path with no typed-array work at all

Each case also has an `_r` twin that first retains a population of the same
shape, so every size class the workload touches is held off its empty boundary
and the SmallObjectSlab cannot churn an arena (P7-00's control, including its
trap: a population that exactly fills its arenas leaves the free list empty and
churns anyway, so the count is deliberately not a multiple of blocks-per-arena).
"""
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cases')
N = 200000
R = 440  # swept: 411 zeroes zjs but leaves qjs at 1.0 arena/op; 440 zeroes both

HEADER = """// Generated by tools/perf/typedarray/gen_cases.py for audit line P7-30.
// Every case wraps its loop in a function so the loop variable is a local slot
// on both engines; a top-level `let` loop is a known zjs-only slow path and
// would contaminate the stage attribution.
"""


def resident(kind):
    if kind is None:
        return ""
    return (
        "// Resident population that keeps every size class this workload touches\n"
        "// off its empty boundary, so the slab never churns an arena. The count is\n"
        "// deliberately not a multiple of blocks-per-arena (P7-00 trap), and was swept\n"
        "// until both engines read ~0 arena events per operation, not just zjs.\n"
        "const keep = [];\n"
        f"for (let i = 0; i < {R}; i++) keep.push({kind});\n"
    )


def emit(name, inner, setup="", res=None, note=""):
    src = HEADER
    if note:
        src += "// " + note + "\n"
    # setup first: a resident population that uses a class declared in setup
    # would otherwise hit that class's TDZ.
    src += setup
    src += resident(res)
    src += "function work(n) {\n    let sink = 0;\n"
    src += f"    for (let i = 0; i < n; i++) {{\n{inner}    }}\n"
    src += "    return sink;\n}\n"
    src += f"print(work({N}));\n"
    with open(os.path.join(OUT, name), 'w') as f:
        f.write(src)


def main():
    os.makedirs(OUT, exist_ok=True)
    emit('noop.js', "        sink += i & 255;\n",
         note="Loop-overhead control: the same loop and the same sink update, no allocation.")

    for k in (0, 8, 32, 33, 40, 64, 512):
        tail = ("        sink += b.length;\n" if k == 0
                else "        b[0] = i & 255;\n        sink += b[0];\n")
        body = f"        const b = new Uint8Array({k});\n" + tail
        emit(f'ta{k}.js', body,
             note=f"Full TypedArray construction with an implicit ArrayBuffer of {k} bytes.")
        emit(f'ta{k}_r.js', body, res=f"new Uint8Array({k})",
             note=f"ta{k} with a resident population so the slab cannot churn.")

    for k in (32, 64):
        body = f"        const b = new ArrayBuffer({k});\n        sink += b.byteLength;\n"
        emit(f'ab{k}.js', body,
             note=f"ArrayBuffer wrapper + backing bytes + zero fill of {k} bytes, no TypedArray view.")
        emit(f'ab{k}_r.js', body, res=f"new ArrayBuffer({k})",
             note=f"ab{k} with a resident population so the slab cannot churn.")

    view = "        const b = new Uint8Array(buf);\n        b[0] = i & 255;\n        sink += b[0];\n"
    emit('taview.js', view, setup="const buf = new ArrayBuffer(64);\n",
         note="TypedArray wrapper + view metadata only: the buffer and its bytes already exist.")
    emit('taview_r.js', view, setup="const buf = new ArrayBuffer(64);\n",
         res="new Uint8Array(buf)",
         note="taview with a resident population so the slab cannot churn.")

    emit('tafill.js',
         "        b.fill(0);\n        b[0] = i & 255;\n        sink += b[0];\n",
         setup="const b = new Uint8Array(64);\n",
         note="Zero fill only: one retained view, no allocation at all.")

    cls = "class C {\n    constructor(x) {\n        this.x = x;\n    }\n}\n"
    body = "        const o = new C(i);\n        sink += o.x & 255;\n"
    emit('classnew.js', body, setup=cls,
         note="Plain user-class construction control: the generic construct path with no typed-array work.")
    emit('classnew_r.js', body, setup=cls, res="new C(0)",
         note="classnew with a resident population.")

    print(len(os.listdir(OUT)), "cases in", OUT)


if __name__ == '__main__':
    main()
